require: rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - bin/*
    - config/*
    - db/**/*
    - node_modules/**/*

  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
    Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
