# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby "2.7.1"

gem "activerecord-import"
gem "bootsnap", ">= 1.4.4", require: false
gem "chartjs-ror"
gem "graphiql-rails", group: :development
gem "graphql"
gem "interactor", "~> 3.0"
gem "jbuilder", "~> 2.7"
gem "jsonapi-serializer"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rails", "~> 6.1.0"
gem "sass-rails", ">= 6"
gem "sidekiq"
gem "sidekiq-scheduler"
gem "sidekiq-unique-jobs"
gem "simplecov", require: false, group: :test
gem "turbolinks", "~> 5"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "webpacker", "~> 5.0"

group :development do
  gem "listen", "~> 3.3"
  gem "pry", "~> 0.13.1"
  gem "rack-mini-profiler", "~> 2.0"
  gem "rubocop-rails", require: false
  gem "spring"
  gem "web-console", ">= 4.1.0"
  gem "webdrivers"
end

group :test do
  gem "action-cable-testing"
  gem "database_cleaner"
  gem "factory_bot_rails"
  gem "jsonapi-rspec"
  gem "mock_redis"
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 4.0.1"
  gem "rspec-sidekiq"
  gem "shoulda-matchers", "~> 4.0"
end
