# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'eventmachine'
gem 'faye-websocket'
gem 'mock_redis'
gem 'redis'
gem 'rspec'
